wrmilling/k3s-gitops

cert-manager/crds/kustomization.yaml, setup/bootstrap-cluster.sh, setup/bootstrap-crds.sh
Moving to a bootstrap script for the CRDs so I can move forward with other components that need attention.
=> 02 23 21 add cert manager to cluster

flux-system-extra/github-alerts/github-alert.yaml, flux-system-extra/github-alerts/github-api-token.template, flux-system-extra/github-alerts/github-api-token.yaml, flux-system-extra/github-alerts/github-provider.yaml, setup/seal-secrets.sh
Should provide the green checkmark on commits based on their completion status.
=> Add alerting back to github on change status

kube-system/authelia/authelia.yaml
Reverts WRMilling/k3s-gitops#49
=> Revert "chore(deps): update helm chart authelia to v0.3.3"

kube-system/authelia/authelia.yaml
Reverts WRMilling/k3s-gitops#55
=> Revert "chore(deps): update helm chart authelia to v0.3.5"

kube-system/authelia/authelia.yaml
Reverts WRMilling/k3s-gitops#58
Going to push the update myself to latest.
=> Revert "chore(deps): update helm chart authelia to v0.3.9"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Reverts WRMilling/k3s-gitops#100 Upgrade problem, revert.
=> Revert "chore(deps): update helm chart kube-prometheus-stack to v15.2.1"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Reverts WRMilling/k3s-gitops#112
=> Revert "chore(deps): update helm chart kube-prometheus-stack to v15.4.3"

flux-system-extra/helm-chart-repositories/appscode-charts.yaml, kube-system/kubedb/kubedb.yaml, setup/bootstrap-crds.sh
Start with Kubedb for Authentik setup, make the database steps easier.
=> Kube system/kubedb

kube-system/authelia/authelia.yaml
Reverts WRMilling/k3s-gitops#125
=> Revert "chore(deps): update helm chart authelia to v0.4.2"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Reverts wrmilling/k3s-gitops#188
=> Revert "chore(deps): update helm chart kube-prometheus-stack to v16.5.0"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Reverts wrmilling/k3s-gitops#191
=> Revert "chore(deps): update helm chart kube-prometheus-stack to v16.6.0"

monitoring/grafana/grafana.yaml
Reverts wrmilling/k3s-gitops#254
=> Revert "chore(deps): update helm chart grafana to v6.13.5"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml
Reverts wrmilling/k3s-gitops#258
=> Revert "chore(deps): update helm chart kube-prometheus-stack to v16.12.0"

kube-system/nginx/nginx-external.yaml, kube-system/nginx/nginx-internal.yaml
Reverts wrmilling/k3s-gitops#255
=> Revert "chore(deps): update helm chart ingress-nginx to v3.34.0"

longhorn-system/longhorn/longhorn.yaml
Reverts wrmilling/k3s-gitops#271
:wat:
=> Revert "chore(deps): update helm chart longhorn to v1.1.2"

longhorn-system/longhorn/longhorn.yaml
Reverts wrmilling/k3s-gitops#273
=> Revert "Revert "chore(deps): update helm chart longhorn to v1.1.2""

kube-system/metallb/metallb.yaml
Reverts wrmilling/k3s-gitops#289
Problem with tolerations in the cart.
=> Revert "chore(deps): update helm chart metallb to v2.4.4"

flux-system/gotk-components.yaml
Reverts wrmilling/k3s-gitops#276
=> Revert "chore(deps): update flux components to v0.16.1 [ci-skip]"

kube-system/nginx/nginx-external.yaml, kube-system/nginx/nginx-internal.yaml
Reverts wrmilling/k3s-gitops#374
=> Revert "chore(deps): update helm chart ingress-nginx to v4"

longhorn-system/longhorn/longhorn.yaml
Reverts wrmilling/k3s-gitops#390
#164
=> Revert "chore(deps): update helm chart longhorn to v1.2.0"

README.md, setup/secrets-templates/velero-helm-values.template, setup/sops-encrypt.sh, velero/README.md, velero/namespace.yaml, velero/velero/crds/kustomizations.yaml, velero/velero/velero-helm-values.sops.yaml, velero/velero/velero.yaml
Partially moves me towards solving #164.
=> Velero: Deploy to cluster

longhorn-system/longhorn/longhorn.yaml
Reverts wrmilling/k3s-gitops#394
=> Revert "Revert "chore(deps): update helm chart longhorn to v1.2.0""

flux-system-extra/discord-alerts/alert.yaml, flux-system-extra/helm-chart-repositories/rook-ceph-charts.yaml, rook-ceph/README.md, rook-ceph/ceph-block/ceph-storageclass.yaml, rook-ceph/ceph-block/cephblockpool.yaml, rook-ceph/ceph-block/snapshotclass.yaml, rook-ceph/chart/rook-ceph-chart.yaml, rook-ceph/chart/rook-ceph-system-psp-user.yaml, rook-ceph/cluster/cluster.yaml, rook-ceph/crds/crds.yaml, rook-ceph/crds/kustomization.yaml, rook-ceph/dashboard/ingress.yaml, rook-ceph/external-snapshotter/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml, rook-ceph/external-snapshotter/crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml, rook-ceph/external-snapshotter/crds/snapshot.storage.k8s.io_volumesnapshots.yaml, rook-ceph/external-snapshotter/snapshot-controller/rbac-snapshot-controller.yaml, rook-ceph/external-snapshotter/snapshot-controller/setup-snapshot-controller.yaml, rook-ceph/monitoring/csi-metrics-service-monitor.yaml, rook-ceph/monitoring/service-monitor.yaml, rook-ceph/namespace.yaml, rook-ceph/toolbox/direct-mount.yaml, rook-ceph/toolbox/toolbox.yaml
Requires further review before merging into master.
=> RookCeph: Creating based off billimek/k8s-gitops

kube-system/authelia/authelia.yaml
Reverts wrmilling/k3s-gitops#484
=> Revert "chore(deps): update helm chart authelia to v0.6.2"

velero/velero/velero.yaml
Reverts wrmilling/k3s-gitops#478
=> Revert "chore(deps): update helm chart velero to v2.23.12"

rook-ceph/chart/rook-ceph-chart.yaml
Reverts wrmilling/k3s-gitops#630
=> Revert "chore(deps): update helm chart rook-ceph to v1.8.0"

default/pihole/pihole.yaml
Reverts wrmilling/k3s-gitops#662
=> Revert "chore(deps): update docker image ekofr/pihole-exporter to v0.1.1"

velero/velero/velero.yaml
Reverts wrmilling/k3s-gitops#675
=> Revert "chore(deps): update helm chart velero to v2.27.2"

monitoring/grafana/grafana.yaml
Reverts wrmilling/k3s-gitops#767
=> Revert "chore(deps): update helm chart grafana to v6.21.3"

monitoring/grafana/grafana.yaml
Reverts wrmilling/k3s-gitops#816
=> Revert "chore(deps): update helm chart grafana to v6.23.0"

default/pihole/pihole.yaml
Reverts wrmilling/k3s-gitops#814
=> Revert "chore(deps): update helm chart pihole to v2.5.8"

rook-ceph/chart/rook-ceph-chart.yaml
Reverts wrmilling/k3s-gitops#1052
=> Revert "chore(deps): update helm chart rook-ceph to v1.9.5"

monitoring/grafana/grafana.yaml
Reverts wrmilling/k3s-gitops#1085
=> Revert "chore(deps): update helm chart grafana to v6.32.1"

rook-ceph/chart/rook-ceph-chart.yaml
Reverts wrmilling/k3s-gitops#1169
=> Revert "chore(deps): update helm chart rook-ceph to v1.9.9"

default/dendrite/dendrite.yaml
Reverts wrmilling/k3s-gitops#1183
=> Revert "chore(deps): update helm chart dendrite to v6.3.1"

default/minio/minio.yaml
Reverts wrmilling/k3s-gitops#1304
=> Revert "feat(charts)!: Update Helm chart minio to 5.0.0"

default/minio/minio.yaml
Reverts wrmilling/k3s-gitops#1310
=> Revert "fix(images): update docker image quay.io/minio/minio to release.2022-10-29t06-21-33z"

default/dendrite/dendrite.yaml, default/freshrss/freshrss.yaml, default/haste-server/haste-server.yaml, default/onedrive/onedrive.yaml, media/nzbget/nzbget.yaml, media/plex/plex.yaml, media/qbittorrent/qbittorrent.yaml, media/radarr/radarr.yaml, media/readarr/readarr.yaml, media/sonarr/sonarr.yaml
Reverts wrmilling/k3s-gitops#1318
=> Revert "feat(charts)!: Update Helm chart app-template to 1.0.1"

default/dendrite/dendrite.yaml, default/freshrss/freshrss.yaml, default/haste-server/haste-server.yaml, default/onedrive/onedrive.yaml, media/nzbget/nzbget.yaml, media/plex/plex.yaml, media/qbittorrent/qbittorrent.yaml, media/radarr/radarr.yaml, media/readarr/readarr.yaml, media/sonarr/sonarr.yaml
Reverts wrmilling/k3s-gitops#1323
=> Revert "Revert "feat(charts)!: Update Helm chart app-template to 1.0.1""

default/dendrite/dendrite.yaml
Reverts wrmilling/k3s-gitops#1325
=> Revert "fix(images): update docker image ghcr.io/matrix-org/dendrite-monolith to v0.10.7"

kube-system/nginx/nginx-external.yaml, kube-system/nginx/nginx-internal.yaml
Reverts wrmilling/k3s-gitops#1336
=> Revert "feat(charts): update helm chart ingress-nginx to 4.4.0"

velero/velero/velero.yaml
Reverts wrmilling/k3s-gitops#1371
=> Revert "feat(images): update docker image velero/velero to v1.10.0"

default/home-assistant/postgres.yaml
Reverts wrmilling/k3s-gitops#1411
=> Revert "feat(images)!: Update Docker image postgres to 15.1"

velero/velero/velero.yaml
Reverts wrmilling/k3s-gitops#1432
=> Revert "feat(charts)!: Update Helm chart velero to 3.1.0"

development/gitea/gitea.yaml
Reverts wrmilling/k3s-gitops#1608
=> Revert "feat(charts)!: Update Helm chart gitea to 8.0.2"

development/forgejo/pvc.yaml
=> Forgejo: Throw more storage at it

development/forgejo/redis.yaml, kube-system/authelia/redis.yaml
Reverts wrmilling/k3s-gitops#2372
=> Revert "fix(helm): update chart redis ( 19.6.2 → 19.6.4 )"

default/onedrive/onedrive.yaml
Reverts wrmilling/k3s-gitops#2515
=> Revert "feat(container): update image driveone/onedrive ( 2.4.25 → 2.5.0 )"

flux-system/gotk-components.yaml
Reverts wrmilling/k3s-gitops#2534
=> Revert "feat(container): update flux group (minor)"

development/forgejo/valkey.yaml, kube-system/authelia/valkey.yaml, social/mastodon/valkey.yaml
Reverts wrmilling/k3s-gitops#2726
=> Revert "feat(helm): update chart valkey ( 2.1.2 → 2.2.1 )"

monitoring/kube-prometheus-stack/kube-prometheus-stack.yaml, monitoring/thanos/thanos.yaml
Reverts wrmilling/k3s-gitops#2727
=> Revert "feat(container): update thanos group"

kube-system/snapshot-controller/snapshot-controller.yaml
Reverts wrmilling/k3s-gitops#2728
=> Revert "feat(helm)!: Update chart snapshot-controller ( 3.0.6 → 4.0.0 )"

development/forgejo/valkey.yaml, kube-system/authelia/valkey.yaml, social/mastodon/valkey.yaml
Reverts wrmilling/k3s-gitops#2911
Valkey Exporter has a failure getting the synced password.
=> Revert "feat(container): update image valkey ( 2.3.0 → 2.4.1 )"

default/pihole/pihole.yaml
Reverts wrmilling/k3s-gitops#2946
=> Revert "feat(helm): update chart pihole ( 2.28.0 → 2.29.0 )"
